### ISSUE TITLE
Support import bbs common with file protocol

### ISSUE THREAD

**Issue by yanivyehu** [deweb-io/vidibate#1]

**Comment by israeldeweb** [comment]
This seems to work for me just fine. What's the problem?

**Comment by israeldeweb** [comment]
Duplicate of https://github.com/deweb-io/bbs-common/issues/1

**Comment by israeldeweb** [comment]
We always fetch from node modules when we are server side, but client side should attempt to get the package from the server before defaulting to the CDN.
