### ISSUE TITLE
Add `newEmbed` route to server

### ISSUE THREAD

**Issue by israeldeweb** [deweb-io/vidibate#6]

**Comment by yanivyehu** [comment]
POST endpoint for record a new (videbate) post in posts table.
the endpoint should get post information (like id - **need to check** when the id is available).

possible primary key: path (for example: a1:a2:a3).

There are two types of posts: 
challenge - the first post of the debate
reply - a response post for challenge/reply.

**Comment by israeldeweb** [comment]
And it's easy to tell the difference, because challenges don't have a separator in their primary key and vice versa.
